{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Base URL."
  },
  "servers": [
    {
      "url": "https://cf-blast.livelikecdn.com/api/v1/"
    }
  ],
  "tags": [],
  "paths": {
    "/new-endpoint": {
      "get": {
        "summary": "New Endpoint",
        "description": "This is your first endpoint! Edit this page to start documenting your API.",
        "operationId": "get_new-endpoint",
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/user-streaks/": {
      "post": {
        "description": "",
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "Created": {
                    "summary": "Created",
                    "value": {
                      "last_activity": "2026-01-02T07:07:00Z",
                      "first_activity": "2026-01-01T07:07:00Z",
                      "track_progress_on": {
                        "target_ids": [
                          "ae06e550-21c4-4e1d-8365-f42309dccdb8"
                        ]
                      },
                      "reason": "Manual correction for missed event",
                      "user_streak": {
                        "id": "77c8115f-66af-4255-a3e1-f6224e76c46c",
                        "url": "http://localhost:8888/api/v1/user-streaks/77c8115f-66af-4255-a3e1-f6224e76c46c/",
                        "profile_id": "405f4a9f-4612-4eea-a7d2-80dbc624f9e2",
                        "streak_id": "49426b34-5c3f-4517-b50f-2be290be472f",
                        "streak": {
                          "id": "49426b34-5c3f-4517-b50f-2be290be472f",
                          "name": "Daily Test - 11 JAN",
                          "period": "daily",
                          "streak_type": "periodic"
                        },
                        "first_activity": "2026-01-01T07:07:00Z",
                        "last_activity": "2026-01-02T07:07:00Z",
                        "reset_at": null,
                        "current_streak_length": 2,
                        "maximum_streak_length": 2,
                        "freeze_start": null,
                        "freeze_until": null,
                        "freeze_reason": null,
                        "milestones_url": "http://localhost:8888/api/v1/user-streaks/77c8115f-66af-4255-a3e1-f6224e76c46c/milestones/",
                        "reason": "Manual correction for missed event"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [],
        "operationId": "post_user-streaks",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "profile_id": {
                    "type": "string"
                  },
                  "streak_id": {
                    "type": "string"
                  },
                  "reason": {
                    "type": "string"
                  },
                  "first_activity": {
                    "type": "string"
                  },
                  "last_activity": {
                    "type": "string"
                  },
                  "track_progress_on": {
                    "type": "object",
                    "properties": {
                      "target_ids": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "required": [
                  "profile_id",
                  "streak_id",
                  "first_activity",
                  "last_activity"
                ]
              }
            }
          }
        }
      }
    },
    "/user-streaks/9cd97f41-d6a0-4dca-a145-993d97746851/progress/": {},
    "/user-streaks/{user-streak-id}/progress/": {
      "patch": {
        "description": "",
        "responses": {
          "200": {
            "description": ""
          },
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "examples": {
                  "Created": {
                    "summary": "Created",
                    "value": {
                      "last_activity": "2026-01-06T07:07:00Z",
                      "track_progress_on": {
                        "target_ids": [
                          "ae06e550-21c4-4e1d-8365-f42309dccdb8",
                          "55528958-dcfc-40e0-943f-b4be50b05be8"
                        ]
                      },
                      "reason": "Manual correction for missed event",
                      "user_streak": {
                        "id": "77c8115f-66af-4255-a3e1-f6224e76c46c",
                        "url": "http://localhost:8888/api/v1/user-streaks/77c8115f-66af-4255-a3e1-f6224e76c46c/",
                        "profile_id": "405f4a9f-4612-4eea-a7d2-80dbc624f9e2",
                        "streak_id": "49426b34-5c3f-4517-b50f-2be290be472f",
                        "streak": {
                          "id": "49426b34-5c3f-4517-b50f-2be290be472f",
                          "name": "Daily Test - 11 JAN",
                          "period": "daily",
                          "streak_type": "periodic"
                        },
                        "first_activity": "2026-01-01T07:07:00Z",
                        "last_activity": "2026-01-06T07:07:00Z",
                        "reset_at": null,
                        "current_streak_length": 6,
                        "maximum_streak_length": 6,
                        "freeze_start": null,
                        "freeze_until": null,
                        "freeze_reason": null,
                        "milestone_count": 2,
                        "milestones_url": "http://localhost:8888/api/v1/user-streaks/77c8115f-66af-4255-a3e1-f6224e76c46c/milestones/",
                        "status": "pending_reset",
                        "reason": "Manual correction for missed event"
                      }
                    }
                  }
                }
              }
            },
            "description": "Created"
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "user-streak-id",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "operationId": "patch_user-streaks-user-streak-id-progress",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "last_activity": {
                    "type": "string"
                  },
                  "reason": {
                    "type": "string"
                  },
                  "track_progress_on": {
                    "type": "object",
                    "properties": {
                      "target_ids": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "required": [
                  "last_activity"
                ]
              }
            }
          }
        }
      }
    },
    "/user-quests/{user-quest-id}": {
      "get": {
        "description": "",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "OK": {
                    "summary": "OK",
                    "value": "{}"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "user-quest-id",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "operationId": "get_user-quests-user-quest-id"
      }
    },
    "/user-streak/{user-streak-id}/reset/": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "OK": {
                    "summary": "OK",
                    "value": {
                      "id": "77b07b0a-c6f5-4c5e-a365-934f9d22c39b",
                      "url": "https://cf-blast-game-changers.livelikecdn.com/api/v1/user-streaks/77b07b0a-c6f5-4c5e-a365-934f9d22c39b/",
                      "profile_id": "12cc3d8f-8ba9-468d-97eb-45c25ccdca6c",
                      "streak_id": "6d2d2c99-767c-489b-b9a8-58de76b0bddc",
                      "streak": {
                        "id": "6d2d2c99-767c-489b-b9a8-58de76b0bddc",
                        "name": "Recurring and repeat on reset test 1",
                        "period": null,
                        "streak_type": "consecutive_action"
                      },
                      "first_activity": "2026-02-16T06:51:07Z",
                      "last_activity": "2026-02-16T06:51:09Z",
                      "reset_at": "2026-02-16T06:51:35.442952Z",
                      "current_streak_length": 1,
                      "maximum_streak_length": 8,
                      "freeze_start": null,
                      "freeze_until": null,
                      "freeze_reason": "",
                      "milestone_count": 0,
                      "milestones_url": "https://cf-blast-game-changers.livelikecdn.com/api/v1/user-streaks/77b07b0a-c6f5-4c5e-a365-934f9d22c39b/milestones/",
                      "status": "reset",
                      "reason": "Reset freeze user streak"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "in": "path",
            "name": "user-streak-id",
            "schema": {
              "type": "string"
            },
            "required": true
          }
        ],
        "operationId": "post_user-streak-user-streak-id-reset",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "reason": {
                    "type": "string"
                  }
                },
                "required": [
                  "reason"
                ]
              }
            }
          }
        }
      }
    },
    "/automation-partners/": {
      "post": {
        "responses": {
          "200": {
            "description": ""
          }
        },
        "parameters": [],
        "summary": "Create Automation Partner",
        "operationId": "post_automation-partners"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "x-readme": {
    "explorer-enabled": true,
    "proxy-enabled": true
  }
}