{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Daily Streaks"
  },
  "servers": [
    {
      "url": "https://cf-blast.livelikecdn.com/api/v1/daily-streaks/"
    }
  ],
  "tags": [],
  "paths": {
    "/new-endpoint": {
      "post": {
        "summary": "New Endpoint",
        "description": "This is your first endpoint! Edit this page to start documenting your API.",
        "operationId": "get_new-endpoint",
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "description": "Unique identifier for Daily Streak Created."
                    }
                  },
                  "required": [
                    "id"
                  ]
                },
                "examples": {
                  "": {
                    "summary": "",
                    "value": {
                      "id": "879fef7a-d403-4c59-ad4b-d3a7b31f53aa",
                      "url": "https://cf-blast.livelikecdn.com/api/v1/daily-streaks/879fef7a-d403-4c59-ad4b-d3a7b31f53aa/",
                      "name": "Delete streak test",
                      "reward_action_key": "poll-voted",
                      "timezone": "Europe/London",
                      "created_at": "2025-09-18T15:57:48.831878Z",
                      "period": "daily",
                      "is_active": true,
                      "client_id": "8PqSNDgIVHnXuJuGte1HdvOjOqhCFE1ZCR3qhqaS",
                      "end_at": null,
                      "attributes": [
                        {
                          "key": "key1",
                          "value": "value1"
                        }
                      ]
                    }
                  },
                  "New Example": {
                    "summary": "New Example",
                    "value": {
                      "id": "879fef7a-d403-4c59-ad4b-d3a7b31f53aa",
                      "url": "https://cf-blast.livelikecdn.com/api/v1/daily-streaks/879fef7a-d403-4c59-ad4b-d3a7b31f53aa/",
                      "name": "Delete streak test",
                      "reward_action_key": "poll-voted",
                      "timezone": "Europe/London",
                      "created_at": "2025-09-18T15:57:48.831878Z",
                      "period": "daily",
                      "is_active": true,
                      "client_id": "8PqSNDgIVHnXuJuGte1HdvOjOqhCFE1ZCR3qhqaS",
                      "end_at": null,
                      "attributes": [
                        {
                          "key": "key1",
                          "value": "value1"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Name of the Daily Streak"
                  },
                  "reward_action_key": {
                    "type": "string",
                    "description": "Reward action key to trigger this daily streak for users."
                  },
                  "client_id": {
                    "type": "string"
                  },
                  "attributes": {
                    "type": "array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        },
                        "value": {
                          "type": "string"
                        }
                      },
                      "type": "object"
                    }
                  }
                },
                "required": [
                  "name",
                  "reward_action_key",
                  "client_id"
                ]
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/new-endpoint-1": {
      "post": {
        "description": "",
        "operationId": "post_new-endpoint-1",
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "url": {
                      "type": "string"
                    },
                    "client_id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "reward_action": {
                      "type": "string"
                    },
                    "timezone": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "period": {
                      "type": "string"
                    },
                    "is_active": {
                      "type": "string"
                    },
                    "end_at": {
                      "type": "string"
                    },
                    "attributes": {
                      "type": "array",
                      "items": {
                        "properties": {
                          "key": {
                            "type": "string"
                          },
                          "value": {
                            "type": "string"
                          }
                        },
                        "type": "object"
                      }
                    }
                  }
                },
                "examples": {
                  "New Example": {
                    "summary": "New Example",
                    "value": {
                      "id": "8c479fe1-761d-4ef3-8d61-91c95066fdd2",
                      "url": "https://cf-blast.livelikecdn.com/api/v1/daily-streaks/8c479fe1-761d-4ef3-8d61-91c95066fdd2/",
                      "name": "Delete streak test",
                      "reward_action_key": "poll-voted",
                      "timezone": "Europe/London",
                      "created_at": "2025-09-18T15:49:16.550946Z",
                      "period": "daily",
                      "is_active": true,
                      "client_id": "FVQI5U57tfCyDV99YjhF3ExdlpiObg5JASvy81Mu",
                      "end_at": null,
                      "attributes": [
                        {
                          "key": "key1",
                          "value": "value1"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Name of the Daily Streak"
                  },
                  "reward_action_key": {
                    "type": "string"
                  },
                  "period": {
                    "type": "string",
                    "enum": [
                      "daily"
                    ]
                  },
                  "client_id": {
                    "type": "string"
                  },
                  "attributes": {
                    "type": "array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        },
                        "value": {
                          "type": "string"
                        }
                      },
                      "type": "object"
                    }
                  }
                },
                "required": [
                  "name",
                  "client_id"
                ]
              }
            }
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "x-readme": {
    "explorer-enabled": true,
    "proxy-enabled": true
  }
}